[package]
authors = ["Josh Holmer <jholmer.in@gmail.com>"]
name = "eureka"
version = "0.1.0"

[dependencies]
log = "0.4.0"
quick-error = "1.1.0"
reqwest = "0.8.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
percent-encoding = "1.0.1"
itertools = "0.7.4"
